name: 'Cancel Workflow Action for failed jobs'
description: 'This Action will cancel all the jobs if any of the jobs failed'
author: vishnudxb
branding:
  icon: 'stop-circle'  
  color: 'red'
inputs:
  repo:
    description: 'Repo details: for eg: octocat/hello-world'
    required: true  
  branch_name:
    description: 'Your GitHub branch'
    required: true
  workflow_file_name:
    description: 'Github Action Workflow file name'
    required: true
  access_token:
    description: 'Your GitHub Access Token, defaults to: {{ github.token }}'
    default: '${{ github.token }}'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.branch_name }}
    - ${{ inputs.workflow_file_name }}
    - ${{ inputs.access_token }}

